# You can pass the robot namespace using the 'name' argument in the launch file
name:
  type: string
  default: "quadruped_1"

$(arg name):
  $(arg name)/joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController

    joints:
      - $(arg name)/front_right_leg1_joint
      - $(arg name)/front_right_leg2_joint
      - $(arg name)/front_right_leg3_joint
      - $(arg name)/front_left_leg1_joint
      - $(arg name)/front_left_leg2_joint
      - $(arg name)/front_left_leg3_joint
      - $(arg name)/back_right_leg1_joint
      - $(arg name)/back_right_leg2_joint
      - $(arg name)/back_right_leg3_joint
      - $(arg name)/back_left_leg1_joint
      - $(arg name)/back_left_leg2_joint
      - $(arg name)/back_left_leg3_joint

    gains:
      $(arg name)/front_right_leg1_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      $(arg name)/front_right_leg2_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      $(arg name)/front_right_leg3_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      $(arg name)/front_left_leg1_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      $(arg name)/front_left_leg2_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      $(arg name)/front_left_leg3_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      $(arg name)/back_right_leg1_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      $(arg name)/back_right_leg2_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      $(arg name)/back_right_leg3_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      $(arg name)/back_left_leg1_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      $(arg name)/back_left_leg2_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
      $(arg name)/back_left_leg3_joint: {p: 200, d: 1, i: 30, i_clamp: 100}
